/* =================================================================
   optimize-images.mjs — makes the photographs light enough to appear
   the instant you scroll to them.

   WHY
     The source files are what came out of the camera or the export:
     3392 px wide, 1.5 MB, for a card that is never drawn wider than
     640 px on a phone. The browser downloads all of it before it can
     paint anything, which is the grey rectangle you see for a beat.

   WHAT IT DOES
     For every photograph in assets/images it writes a set of WebP
     copies at sane widths into assets/opt/ (the source files are never
     touched — the lightbox and any download still get the original),
     then writes assets/opt/manifest.js: one entry per original,
     carrying its real pixel size and the copies that exist. lib.jsx
     reads that manifest and hands the browser a <picture> with a
     srcset, so a phone downloads the 480 px copy and a retina desktop
     the 1440 px one.

   USAGE
     npm run images          only what changed
     npm run images -- --all rebuild everything

   NEEDS  sips (ships with macOS) for the sizes, cwebp for the encode
          (`brew install webp`). The output is committed, so the site
          builds and deploys without either of them.
   ================================================================= */

import { readdir, stat, writeFile, mkdir, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';

const run = promisify(execFile);

const SRC_DIR = 'assets/images';
const OUT_DIR = 'assets/opt';
const WIDTHS  = [480, 720, 960, 1440, 1920];
const QUALITY = 82;
const ALL     = process.argv.includes('--all');

// Marks, icons and the social card are either tiny already or must stay
// byte-for-byte what they are; only photographs go through here.
const SKIP = new Set(['og-image.jpg', 'avatar.png']);

async function walk(dir){
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })){
    if (entry.name.startsWith('.')) continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await walk(p));
    else if (/\.(jpe?g|png)$/i.test(entry.name) && !SKIP.has(entry.name)) out.push(p);
  }
  return out;
}

async function size(file){
  const { stdout } = await run('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', file]);
  const w = +(stdout.match(/pixelWidth:\s*(\d+)/) || [])[1];
  const h = +(stdout.match(/pixelHeight:\s*(\d+)/) || [])[1];
  return { w, h };
}

async function main(){
  if (!existsSync(SRC_DIR)) return;
  const files = (await walk(SRC_DIR)).sort();
  const manifest = {};
  const skipped = [];
  let written = 0, kept = 0, bytesIn = 0, bytesOut = 0;

  for (const file of files){
    const { w, h } = await size(file);
    if (!w || !h) continue;
    const src = '/' + file;
    const rel = path.relative(SRC_DIR, file);
    const base = path.join(OUT_DIR, rel).replace(/\.(jpe?g|png)$/i, '');
    await mkdir(path.dirname(base), { recursive: true });

    // Never upscale, and always offer the original width (capped) so a
    // retina screen still has something sharp to pick.
    const widths = [...new Set(WIDTHS.filter(x => x < w).concat(Math.min(w, WIDTHS[WIDTHS.length - 1])))]
      .sort((a, b) => a - b);

    const srcStat = await stat(file);
    const variants = [];
    let failed = null;
    for (const width of widths){
      const out = `${base}-${width}.webp`;
      const fresh = !ALL && existsSync(out) && (await stat(out)).mtimeMs > srcStat.mtimeMs;
      if (fresh) kept++;
      else {
        try {
          await run('cwebp', ['-quiet', '-q', String(QUALITY), '-m', '6', '-sharp_yuv',
                              '-resize', String(width), '0', file, '-o', out]);
          written++;
        } catch (err) {
          /* One file the encoder cannot read used to abort the whole run, so a
             single bad download left every image after it unprocessed — and
             the originals being served raw is invisible until someone looks at
             the network tab. Skip it, name it at the end, keep going.
             Nearly always a file saved from a browser with a lying extension:
             an AVIF called .png, a WebP called .jpg. `file <name>` tells you. */
          failed = err;
          break;
        }
      }
      bytesOut += (await stat(out)).size;
      variants.push([width, '/' + out]);
    }
    if (failed || !variants.length){
      skipped.push(file);
      continue;                      // no manifest entry: <Img> serves the original
    }
    bytesIn += srcStat.size;
    manifest[src] = { w, h, v: variants };
  }

  await mkdir(OUT_DIR, { recursive: true });
  const js = '/* Generated by tools/optimize-images.mjs — do not edit. */\n'
           + 'window.IMG_MANIFEST = ' + JSON.stringify(manifest, null, 0) + ';\n';
  await writeFile(path.join(OUT_DIR, 'manifest.js'), js);

  const mb = n => (n / 1048576).toFixed(1) + ' MB';
  console.log(`✓ ${files.length - skipped.length} images · ${written} encoded, ${kept} already current`);
  console.log(`  originals ${mb(bytesIn)} → webp set ${mb(bytesOut)} (all widths together)`);
  if (skipped.length){
    console.warn(`⚠ could not encode ${skipped.length}, served at full size until fixed:`);
    for (const f of skipped) console.warn(`    ${f}   — check its real type with \`file ${f}\``);
  }
}

main().catch(err => {
  if (err && err.code === 'ENOENT') {
    console.error('Missing sips or cwebp. Install the encoder with:  brew install webp');
  } else console.error(err);
  process.exit(1);
});
