// =============================================================================
//  lib.jsx — the shared toolbox: data accessors, routing, dates, reveals.
//  Loaded first; everything it exports lands on `window` at the bottom so the
//  other files (home / work / about / contact / app) can use it directly.
// =============================================================================

const { useState, useEffect, useMemo, useRef, useCallback } = React;

/* ── Data ──────────────────────────────────────────────────────────────── */
const DATA    = () => window.PORTFOLIO_DATA || {};
const PROFILE = () => DATA().profile  || {};
const PROJS   = () => DATA().projects || [];

// The few lines of page copy that aren't project content. Defaults live in the
// components; add a `copy: { … }` object in data.js to override any of them.
const COPY = (key, fallback) => (DATA().copy || {})[key] || fallback;

/* ── Small maths ───────────────────────────────────────────────────────── */
const clamp  = (v, a, b) => Math.max(a, Math.min(b, v));
const lerp   = (a, b, t) => a + (b - a) * t;
const smooth = t => { t = clamp(t, 0, 1); return t * t * (3 - 2 * t); };
const easeIO = t => { t = clamp(t, 0, 1); return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; };
const easeOut = t => 1 - Math.pow(1 - clamp(t, 0, 1), 3);

// Radius of the circle centred on (cx,cy) that covers the whole viewport —
// what the intro veil needs to grow to before it can hold the screen.
function coverRadius(cx, cy, w, h){
  return Math.max(
    Math.hypot(cx, cy), Math.hypot(w - cx, cy),
    Math.hypot(cx, h - cy), Math.hypot(w - cx, h - cy)
  );
}

const reduceMotion = () => window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function useMedia(query){
  const [match, setMatch] = useState(() => window.matchMedia(query).matches);
  useEffect(() => {
    const mq = window.matchMedia(query);
    const on = e => setMatch(e.matches);
    mq.addEventListener('change', on);
    setMatch(mq.matches);
    return () => mq.removeEventListener('change', on);
  }, [query]);
  return match;
}

/* ── Routing ───────────────────────────────────────────────────────────────
   Real paths, not hashes: /work/, /work/f1/, /about/, /contact/. Every one of
   them is a real file on the server (generated by tools/build.mjs), so a
   shared link previews with the right title and image. Old #/work/f1 links
   are rewritten to the new form on boot (see index.html). */
function parsePath(pathname){
  const parts = String(pathname || '/').replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
  if (!parts.length) return { route: 'home', sub: '' };
  const r = parts[0].toLowerCase();
  if (r === 'work')    return { route: 'work', sub: (parts[1] || '').toLowerCase() };
  if (r === 'about')   return { route: 'about', sub: '' };
  if (r === 'contact') return { route: 'contact', sub: '' };
  return { route: '404', sub: '' };
}
const pathFor     = (route, sub) => route === 'home' ? '/' : '/' + route + (sub ? '/' + sub : '') + '/';
const projectPath = id => '/work/' + id + '/';

// An <a> that navigates in-app on a plain left click, and behaves like a
// normal link for everything else (new tab, middle click, crawlers).
function Link({ to, children, className, onClick, ...rest }){
  return (
    <a href={to} className={className} {...rest}
       onClick={e => {
         if (onClick) onClick(e);
         if (e.defaultPrevented) return;
         if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
         if (rest.target === '_blank') return;
         e.preventDefault();
         if (window.__nav) window.__nav(to);
       }}>
      {children}
    </a>
  );
}

// Smooth scroll that goes through Lenis when it is running.
function scrollToEl(el, offset){
  if (!el) return;
  const off = offset == null ? -84 : offset;
  if (window.__lenis) { window.__lenis.scrollTo(el, { offset: off, duration: 1.1 }); return; }
  const y = el.getBoundingClientRect().top + window.scrollY + off;
  window.scrollTo({ top: y, behavior: reduceMotion() ? 'instant' : 'smooth' });
}

/* ── Time ──────────────────────────────────────────────────────────────── */
function brusselsTime(){
  try {
    return new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Europe/Brussels' }).format(new Date());
  } catch (e) {
    return new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date());
  }
}
function useClock(){
  const [t, setT] = useState(brusselsTime);
  useEffect(() => {
    const id = setInterval(() => setT(brusselsTime()), 30000);
    return () => clearInterval(id);
  }, []);
  return t;
}

// Live age from an ISO date of birth ("YYYY-MM-DD").
function computeAge(birth){
  const d = new Date(birth);
  if (isNaN(d.getTime())) return null;
  const now = new Date();
  let a = now.getFullYear() - d.getFullYear();
  const m = now.getMonth() - d.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < d.getDate())) a--;
  return a;
}

/* ── Project dates ─────────────────────────────────────────────────────── */
function parseProjDate(s){
  if (!s) return null;
  let str = String(s).trim();
  if (/^\d{4}-\d{2}$/.test(str)) str += '-01';
  const t = Date.parse(str);
  return isNaN(t) ? null : new Date(t);
}
function projDateLabel(p){
  const d = parseProjDate(p.date);
  if (d){
    const hasDay = /^\d{4}-\d{2}-\d{2}/.test(String(p.date).trim());
    return d.toLocaleDateString('en-GB', { day: hasDay ? 'numeric' : undefined, month: 'short', year: 'numeric', timeZone: 'UTC' });
  }
  return p.year || '';
}
function projDateKey(p){
  const d = parseProjDate(p.date);
  if (d) return d.getTime();
  const yrs = String(p.year || '').match(/\d{4}/g);
  const y = yrs ? Math.max.apply(null, yrs.map(Number)) : 0;
  return y ? Date.UTC(y, 11, 31) : 0;
}
// The span of years covered by the projects, for the Work page eyebrow.
function projectYears(){
  const ys = PROJS().map(p => new Date(projDateKey(p)).getUTCFullYear()).filter(Boolean);
  if (!ys.length) return '';
  const lo = Math.min.apply(null, ys), hi = Math.max.apply(null, ys);
  return lo === hi ? String(lo) : lo + ' — ' + hi;
}

/* ── Timeline periods ───────────────────────────────────────────────────
   "2025-09 — Present", "2022-09 — 2025-06", "Fall 2026" … Only an em/en dash
   surrounded by spaces separates the two sides, so ISO dates stay intact. */
const PERIOD_SPLIT = /\s+[—–]\s+/;
function formatPeriodPart(s){
  s = String(s).trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return new Date(s + 'T00:00:00Z').toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });
  if (/^\d{4}-\d{2}$/.test(s))       return new Date(s + '-01T00:00:00Z').toLocaleDateString('en-GB', { month: 'short', year: 'numeric', timeZone: 'UTC' });
  return s;
}
const formatPeriod = period => String(period || '').split(PERIOD_SPLIT).map(formatPeriodPart).join(' — ');
function periodStartKey(period){
  const first = String(period || '').split(PERIOD_SPLIT)[0].trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(first)) return Date.parse(first + 'T00:00:00Z');
  if (/^\d{4}-\d{2}$/.test(first))       return Date.parse(first + '-01T00:00:00Z');
  const m = first.match(/\d{4}/);
  return m ? Date.UTC(+m[0], 0, 1) : 0;
}
function periodEndKey(period){
  const parts = String(period || '').split(PERIOD_SPLIT);
  const last  = (parts[parts.length - 1] || '').trim();
  if (parts.length < 2 || /present|now|today|ongoing/i.test(last)) return Date.now();
  if (/^\d{4}-\d{2}-\d{2}$/.test(last)) return Date.parse(last + 'T00:00:00Z');
  if (/^\d{4}-\d{2}$/.test(last)){
    const d = new Date(last + '-01T00:00:00Z');
    return Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0);   // end of that month
  }
  const m = last.match(/\d{4}/);
  if (m) return Date.UTC(+m[0], 11, 31);
  return periodStartKey(period) + 90 * 864e5;
}
// The timeline entries, oldest first, with their real start/end in ms.
function timelineEntries(){
  const now = Date.now();
  return (PROFILE().timeline || []).map(e => {
    const start = periodStartKey(e.period);
    let end = periodEndKey(e.period);
    if (end < start) end = start + 30 * 864e5;
    return Object.assign({}, e, { start, end, upcoming: start > now, current: start <= now && now <= end });
  }).sort((a, b) => a.start - b.start);
}

/* ── CV files ───────────────────────────────────────────────────────────
   data.js may declare one PDF per language; a language whose file is missing
   from /assets/cv is dropped from the menu, so the site follows the files you
   actually ship. Probing fails open (offline, file://) — a link is never
   hidden by accident. */
const CV_LANGS = [['en', 'English'], ['fr', 'Français'], ['nl', 'Nederlands']];
function cvDeclared(P){
  const cv = (P || {}).cv;
  if (!cv) return [];
  if (typeof cv === 'string') return (cv && cv !== '#') ? [{ lang: 'en', label: 'CV', href: cv }] : [];
  return CV_LANGS.map(([lang, label]) => (cv[lang] && cv[lang] !== '#') ? { lang, label, href: cv[lang] } : null).filter(Boolean);
}
const cvFound  = new Map();
const cvProbes = new Map();
function cvProbe(href){
  if (cvProbes.has(href)) return cvProbes.get(href);
  const sameOrigin = !/^[a-z]+:\/\//i.test(href) && !href.startsWith('//');
  const canProbe = sameOrigin && typeof fetch === 'function' && typeof location !== 'undefined' && location.protocol !== 'file:';
  const p = (canProbe ? fetch(href, { method: 'HEAD' }).then(r => r.ok).catch(() => true) : Promise.resolve(true))
    .then(ok => { cvFound.set(href, ok); return ok; });
  cvProbes.set(href, p);
  return p;
}
const cvLinks = P => cvDeclared(P).filter(c => cvFound.get(c.href) !== false);
function cvLinksReady(P){
  const declared = cvDeclared(P);
  return Promise.all(declared.map(c => cvProbe(c.href))).then(ok => declared.filter((c, i) => ok[i]));
}
function cvPrimary(P){ const l = cvLinks(P); return l.length ? l[0].href : null; }
function useCvLinks(){
  const P = PROFILE();
  const [links, setLinks] = useState(() => cvLinks(P));
  useEffect(() => {
    let alive = true;
    cvLinksReady(P).then(l => { if (alive) setLinks(l); });
    return () => { alive = false; };
  }, []);
  return links;
}

/* ── Project fields ────────────────────────────────────────────────────── */
const isImageCover = c => !!c && (c.startsWith('http://') || c.startsWith('https://') || c.startsWith('/'));

function projById(id){ return PROJS().find(p => p.id === id) || null; }

// "F1 Duel — Prediction Game & Race Predictor" → ["F1 Duel", "Prediction …"]
function splitTitle(p){
  const parts = String(p.title || '').split(PERIOD_SPLIT);
  if (parts.length > 1) return [parts[0], parts.slice(1).join(' — ')];
  return [String(p.title || ''), ''];
}

function projLinks(p){
  const out = [];
  if (p.github && p.github !== '#') out.push({ url: p.github, label: null });
  (Array.isArray(p.links) ? p.links : []).forEach(l => { if (l && l.url && l.url !== '#') out.push({ url: l.url, label: l.label || null }); });
  const seen = new Set();
  return out.filter(l => { if (seen.has(l.url)) return false; seen.add(l.url); return true; });
}
function linkKind(url){
  if (!url || url === '#') return null;
  if (/notion\./i.test(url)) return { icon: 'Notion', label: 'Notion' };
  if (/github\./i.test(url)) return { icon: 'Github', label: 'GitHub' };
  return { icon: 'ArrowUR', label: 'Link' };
}
function projSections(p){
  if (Array.isArray(p.sections) && p.sections.length) return p.sections;
  const out = [];
  const intro = p.long || p.summary;
  if (intro) out.push({ title: 'Overview', body: [intro] });
  if (Array.isArray(p.highlights) && p.highlights.length) out.push({ title: 'Key points', list: p.highlights });
  return out;
}
function projSkills(p){
  return (Array.isArray(p.skills) ? p.skills : [])
    .map(s => typeof s === 'string' ? { name: s, note: '' } : s)
    .filter(s => s && s.name);
}
function projGallery(p){
  return (Array.isArray(p.gallery) ? p.gallery : [])
    .map(g => typeof g === 'string' ? { src: g, caption: '' } : g)
    .filter(g => g && g.src);
}
const ATT_TYPES = {
  pdf:'PDF', doc:'Doc', docx:'Doc', odt:'Doc', rtf:'Doc', txt:'Doc', md:'Doc',
  ppt:'Slides', pptx:'Slides', key:'Slides', odp:'Slides',
  xls:'Sheet', xlsx:'Sheet', ods:'Sheet', csv:'Data', json:'Data',
  zip:'Archive', rar:'Archive', '7z':'Archive', tar:'Archive', gz:'Archive',
  ipynb:'Notebook', py:'Code', r:'Code', sql:'Code',
  slides:'Slides', report:'Report', paper:'Report', sheet:'Sheet',
  data:'Data', dataset:'Data', code:'Code', notebook:'Notebook',
  archive:'Archive', poster:'Poster', video:'Video', link:'Link',
};
const ATT_ICONS = {
  PDF:'FileDoc', Doc:'FileDoc', Report:'FileDoc', Poster:'FileDoc',
  Slides:'FileSlides', Video:'FileSlides',
  Sheet:'FileSheet', Data:'FileSheet',
  Archive:'FileZip', Code:'FileCode', Notebook:'FileCode', Link:'FileLink',
};
function projAttachments(p){
  return (Array.isArray(p.attachments) ? p.attachments : [])
    .map(a => typeof a === 'string' ? { url: a } : a)
    .map(a => Object.assign({}, a, { url: (a && (a.url || a.file)) || '' }))
    .filter(a => a.url && a.url !== '#')
    .map(a => {
      const clean = a.url.split(/[?#]/)[0];
      const ext   = (clean.match(/\.([a-z0-9]+)$/i) || [])[1] || '';
      const key   = String(a.type || ext).toLowerCase();
      const kind  = ATT_TYPES[key] || (a.type ? a.type : 'Link');
      return {
        url: a.url,
        label: a.label || decodeURIComponent(clean.split('/').pop()) || kind,
        note: a.note || '',
        kind,
        icon: ATT_ICONS[kind] || 'FileLink',
        local: !/^(https?:)?\/\//i.test(a.url),
      };
    });
}

/* ── Text helpers ──────────────────────────────────────────────────────────
   In data.js, *asterisks* set a few words in the italic serif — the "voice"
   of the charter. Used by the home intro. */
function emphasise(text){
  return String(text || '').split(/\*([^*]+)\*/g).map((chunk, i) => {
    if (!chunk) return null;
    return i % 2 ? <em key={i}>{chunk}</em> : <React.Fragment key={i}>{chunk}</React.Fragment>;
  });
}
// Same string, but as one span per word so the scroll can fill them in turn.
function fillWords(text){
  const out = [];
  String(text || '').split(/\*([^*]+)\*/g).forEach((chunk, i) => {
    if (!chunk) return;
    const em = i % 2 === 1;
    chunk.split(/\s+/).filter(Boolean).forEach(w => out.push({ w, em }));
  });
  return out;
}

/* ── Reveals ───────────────────────────────────────────────────────────────
   Anything with .rv gets .in the first time it enters the viewport; the CSS
   does the rest. With reduced motion (or no observer) everything is shown at
   once — the page never depends on the animation to be readable. */
function useReveals(rootRef, deps){
  useEffect(() => {
    const root = (rootRef && rootRef.current) || document.body;
    const els = Array.prototype.slice.call(root.querySelectorAll('.rv:not(.in)'));
    if (!els.length) return;
    if (reduceMotion() || typeof IntersectionObserver === 'undefined'){
      els.forEach(el => el.classList.add('in'));
      return;
    }
    const io = new IntersectionObserver(entries => {
      entries.forEach(en => { if (en.isIntersecting){ en.target.classList.add('in'); io.unobserve(en.target); } });
    }, { rootMargin: '0px 0px -10% 0px', threshold: 0 });
    els.forEach(el => io.observe(el));
    return () => io.disconnect();
  }, deps || []);
}

// One rAF-throttled callback for scroll + resize, run once on mount.
function useScrollFrame(fn, deps){
  useEffect(() => {
    let raf = 0;
    const run = () => { raf = 0; fn(); };
    const schedule = () => { if (!raf) raf = requestAnimationFrame(run); };
    run();
    window.addEventListener('scroll', schedule, { passive: true });
    window.addEventListener('resize', schedule);
    return () => {
      window.removeEventListener('scroll', schedule);
      window.removeEventListener('resize', schedule);
      if (raf) cancelAnimationFrame(raf);
    };
  }, deps || []);
}

/* ── Small components ──────────────────────────────────────────────────── */

// A title whose words rise out of a mask, with the orange dot as its period.
// The dot sits OUTSIDE the mask: the mask has to clip (that is what makes the
// word rise out of nothing) and the dot has to be free to grow — the home
// hand-off scales it up to catch the orange page. `.wn` keeps the two glued
// on the same line.
function Words({ text, className, delay, dot, dotId, as }){
  const Tag = as || 'span';
  const words = String(text || '').split(/\s+/).filter(Boolean);
  return (
    <Tag className={['words rv', className].filter(Boolean).join(' ')} style={{ '--d': (delay || 0) + 's' }}>
      {words.map((w, i) => {
        const last = i === words.length - 1;
        const word = <span className="w"><span className="wi" style={{ '--i': i }}>{w}</span></span>;
        return (
          <React.Fragment key={i}>
            {dot && last
              ? <span className="wn">{word}<span className="dot" id={dotId}/></span>
              : word}
            {last ? null : ' '}
          </React.Fragment>
        );
      })}
    </Tag>
  );
}

/* ── Photographs ───────────────────────────────────────────────────────────
   Everything the browser needs to paint a picture without making you wait:
   the WebP copies written by tools/optimize-images.mjs (a phone downloads
   the 480 px one, not the 3392 px original) and the real pixel size, so the
   box is already the right shape before a single byte arrives. With no
   manifest the original is served on its own — nothing breaks, it is just
   heavier. */
function imgSet(src){
  const m = window.IMG_MANIFEST ? window.IMG_MANIFEST[src] : null;
  if (!m || !m.v || !m.v.length) return null;
  return { w: m.w, h: m.h, srcset: m.v.map(v => v[1] + ' ' + v[0] + 'w').join(', ') };
}

function Img({ src, alt, sizes, eager, priority, onLoad }){
  const set = imgSet(src);
  const img = (
    <img src={src} alt={alt || ''} onLoad={onLoad} decoding="async"
         width={set ? set.w : undefined} height={set ? set.h : undefined}
         loading={eager ? 'eager' : 'lazy'} fetchpriority={priority ? 'high' : undefined}/>
  );
  if (!set) return img;
  return (
    <picture>
      <source type="image/webp" srcSet={set.srcset} sizes={sizes || '100vw'}/>
      {img}
    </picture>
  );
}

// A project cover: an image path, or one of the SVG artworks in covers.jsx.
function CoverArt({ cover, title, eager, priority, sizes }){
  if (isImageCover(cover)) {
    return <Img src={cover} alt={title || ''} sizes={sizes} eager={eager} priority={priority}/>;
  }
  const Comp = window.Cover ? (window.Cover[cover] || window.Cover.Generic) : null;
  return Comp ? <Comp/> : null;
}

// The rotating scroll badge in the hero.
let badgeSeq = 0;
function ScrollBadge({ label, className }){
  const id = useMemo(() => 'ring-' + (++badgeSeq), []);
  const text = ((label || 'Scroll to explore') + ' · ').toUpperCase().repeat(2);
  return (
    <svg className={className || 'hero-badge'} viewBox="0 0 100 100" aria-hidden="true">
      <defs><path id={id} d="M50,50 m-39,0 a39,39 0 1,1 78,0 a39,39 0 1,1 -78,0"/></defs>
      <g className="badge-ring"><text><textPath href={'#' + id} textLength="242" lengthAdjust="spacing">{text}</textPath></text></g>
      <circle className="badge-core" cx="50" cy="50" r="16"/>
      <path className="badge-arrow" d="M50 43v14M44.5 51.5 50 57l5.5-5.5"/>
    </svg>
  );
}

// One project card — the Majd grid unit. `size="sm"` is the Work page.
// The two grids are different widths, so each tells the browser which copy of
// the cover it actually needs.
const CARD_SIZES = {
  lg: '(max-width:720px) calc(100vw - 2 * clamp(24px,4.6vw,48px)), (max-width:1360px) 46vw, 610px',
  sm: '(max-width:560px) calc(100vw - 2 * clamp(24px,4.6vw,48px)), (max-width:980px) 46vw, 400px',
};
function ProjectCard({ p, size, delay, flag, eager }){
  const [main, dashSub] = splitTitle(p);
  const small = size === 'sm';
  const sub = dashSub || (small ? p.cat : p.cat + ' · ' + projDateLabel(p));
  return (
    <Link to={projectPath(p.id)} className={'pcard' + (small ? ' sm' : '')} aria-label={p.title}>
      <div className="pcard-media rv rv-media" style={{ '--d': (delay || 0) + 's' }}>
        <CoverArt cover={p.cover} title={p.title} eager={eager} sizes={small ? CARD_SIZES.sm : CARD_SIZES.lg}/>
        {flag ? <span className="flag">Featured</span> : null}
      </div>
      <div className="pcard-text rv rv-up" style={{ '--d': ((delay || 0) + .08) + 's' }}>
        <div className="pcard-row">
          <div>
            <h3 className="pcard-title">{main}<Icon.ArrowUR/></h3>
            {sub ? <p className="pcard-sub">{sub}</p> : null}
          </div>
          {small ? <span className="pcard-date">{projDateLabel(p)}</span> : null}
        </div>
      </div>
    </Link>
  );
}

Object.assign(window, {
  DATA, PROFILE, PROJS, COPY,
  clamp, lerp, smooth, easeIO, easeOut, coverRadius, reduceMotion, useMedia,
  parsePath, pathFor, projectPath, Link, scrollToEl,
  brusselsTime, useClock, computeAge,
  parseProjDate, projDateLabel, projDateKey, projectYears,
  formatPeriod, periodStartKey, periodEndKey, timelineEntries,
  cvLinks, cvLinksReady, cvPrimary, useCvLinks,
  isImageCover, projById, splitTitle, projLinks, linkKind, projSections,
  projSkills, projGallery, projAttachments,
  emphasise, fillWords,
  useReveals, useScrollFrame,
  Words, Img, CoverArt, ScrollBadge, ProjectCard,
});
